### ISSUE TITLE
Rubocopを導入する

### ISSUE THREAD

**Issue by shirotamaki** [shirotamaki/outdoor-heart-sutra#13]
Gemfileへ次のように記述する

```rb
group :development do
  gem 'rubocop-fjord', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec', require: false
end

```

`.rubocop.yml`の設定は以下とする。

```yml
inherit_gem:
  rubocop-fjord:
    - config/rubocop.yml
    - config/rails.yml

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/ClassLength:
  Exclude:
    - spec/**/*

Rails/FilePath:
  Exclude:
    - spec/**/*

AllCops:
  Exclude:
    - '**/templates/**/*'
    - '**/vendor/**/*'
    - app/views/**/*
    - config/**/*
    - config.ru
    - node_modules/**/*
    - db/migrate/*
    - db/schema.rb
    - storage/**/*
    - tmp/**/*
    - bin/**/*

```
