### ISSUE TITLE
indexページの経文を縦書きレイアウトにして並べる

### ISSUE THREAD

**Issue by shirotamaki** [shirotamaki/outdoor-heart-sutra#236]
## 経文を縦書きレイアウトにして並べる

![image.png](https://bootcamp.fjord.jp/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMThMQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4704c8a926d7378f2e4327f4ed771307d6036e4b/image.png)
TailwindCSSでは、縦書きかつ右から左へ折り返す並べ方を扱えるクラスが存在しない。そのためCSSを直書きし取り込むことで対応した。

```css
/* frontend/src/styles/globals.css */

.vertical-sutra-container {
  direction: rtl;
  display: grid;
  grid-auto-flow: column;
  grid-template-rows: repeat(10, auto);
}
```

`direction: rtl;`
 rtlは、right-to-leftのを示している。これは要素が右から左へ流れることを意味する

`grid-template-rows: repeat(10, auto);`
gridの行の数とサイズを定義する。gridの数は10個（行）としサイズはautoで自動的に決まるように設定した。その場合漢字一文字のサイズに依存するので、現状は48pxの高さにしている。
![Top___アウトドア般若心経.png](https://bootcamp.fjord.jp/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmNMQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dcbd806d21ed868f6c68e044da9f0eb5eeff2cde/Top___%E3%82%A2%E3%82%A6%E3%83%88%E3%83%88%E3%82%99%E3%82%A2%E8%88%AC%E8%8B%A5%E5%BF%83%E7%B5%8C.png)

## 参考
- [direction \- CSS: カスケーディングスタイルシート \| MDN](https://developer.mozilla.org/ja/docs/Web/CSS/direction)
- [grid \- CSS: カスケーディングスタイルシート \| MDN](https://developer.mozilla.org/ja/docs/Web/CSS/grid)
- [grid\-template\-rows \- CSS: カスケーディングスタイルシート \| MDN](https://developer.mozilla.org/ja/docs/Web/CSS/grid-template-rows)
