### ISSUE TITLE
GitHub ActionsでFly.ioへのデプロイを自動化する

### ISSUE THREAD

**Issue by shirotamaki** [shirotamaki/outdoor-heart-sutra#60]
### 1. API Tokenを発行する。
公式だと` flyctl tokens create deploy -x 999999h`と書いてあるがうまくいかず。`fly auth token`だとすべてを管理しているらしくこれでも良さそうなのでチョイスした。

> Whereas API tokens (fly auth token) can manage all of your organizations' apps, deploy tokens are limited to a single application.
https://fly.io/docs/reference/deploy-tokens/

```
❯ flyctl auth token
   fo1_hogehogehogehogehogehogheohgoeh
```

### 2. 取得したトークンをFLY_API_TOKENとしてGitHub上のリポジトリのRepository secretsに追加する。

![Image](https://github.com/shirotamaki/outdoor-heart-sutra/assets/65638955/c233fae4-66b9-4cf7-b89e-95a21ac6cae4)

### 3. flyctl launchを実行しfly.tomlを作成し直す

> Run flyctl launch to create a fly.toml configuration file. Say N to adding databases and N to immediate deployment.

### 4. fly.ymlを用意する

```
// .github/workflows/fly.yml


name: Fly Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        working-directory: ./backend                                              // fly.ymlの位置を指定する
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

```

### 5. 変更した内容をコミットしpush。その後手元でデプロイまで行う

```
❯ fly deploy
```

## 参考
https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/
